# This is a basic workflow to help you get started with Actions

name: Deploy_23_05_2020

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  my_test_depl:
    runs-on: ubuntu-latest 
    steps:
   - name: Print TEST MESSAGE
     run : echo "TEST MESSAGE"

  my_test_depl2: 
    runs-on: ubuntu-latest
    steps:
      - name: Print TEST_MESSAGE ver2.0
        run: echo "TEST_MESSAGE ver2.0"
  my_test_depl3:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nginx
        run: apt-get install nginx
