name: Deploy_23_05_2020
env:
  App_name    : "My DEPL"
  Depl_PACKAGE_Name: "DEPL ver 2.0 - ${{ github.sha }}"  
on: 
  push:
    branches: 
      - master
jobs:

  my_test_depl:
    runs-on: ubuntu-latest 
    steps:
      - name: Print TEST MESSAGE
        run : echo "TEST MESSAGE"
        
      - name: start few commands
        run : |
          echo "Mes1"
          echo "Mes2"
          echo "APP name: ${{ env.App_name }}"

  my_test_depl2: 
    runs-on: ubuntu-latest
    steps:
      - name: Print TEST_MESSAGE ver2.0
        run: echo "TEST_MESSAGE ver2.0"
      - name: Print Second env val
        run: echo "DEPL_PACKAGE_NAME is ${{ env.Depl_PACKAGE_Name }}"
        
  my_test_depl3:
    runs-on: ubuntu-latest
    needs: [my_test_depl, my_test_depl2]
    steps:
      - name: Git clone my repo
        uses: action/checkout@v1
      - name: List of files
        run: ls -la
    
